### ISSUE TITLE
nposix.c:638:2: error: #error "Please implement __mg_os_start_time and __mg_os_get_time_ticks for your OS"

### ISSUE THREAD

**Issue by maikebing** [VincentWei/build-minigui-5.0#1]
nposix.c:638:2: error: #error "Please implement __mg_os_start_time and __mg_os_get_time_ticks for your OS"

Linux Version: Debian GNU/Linux 7 (wheezy)
Gcc Version: gcc version 4.7.2 (Debian 4.7.2-5)

**Comment by VincentWei** [comment]
this error appears when there is no implementation for a specific operating system. The source code depends on a macro such as `__LINUX__`. Please check the mgconfig.h file auto-generated by the configure scripts.
