### ISSUE TITLE
./build-minigui. sh  report errors

### ISSUE THREAD

**Issue by htk719809837** [VincentWei/build-minigui-5.0#10]
When I try to build MiniGUI 5.0 in Ubuntu 18.04.6 LTS 0, enter command ./build-minigui. sh ， reporting errors。i am a novice developer, wants to try minigui5, thanks for your reply
![image](https://user-images.githubusercontent.com/62541077/164873279-bc747141-f4c8-42ac-ad84-82a9db85d0ef.png)

**Comment by htk719809837** [comment]
The same problem was not found on minigui 4.0

**Comment by htk719809837** [comment]
vim build-minigui.sh    add --disable-videodrm can make can  work, but how to fix this mistake

**Comment by VincentWei** [comment]
This compilation error caused by a typo: the type of `size` should be `size_t` instead of `unsigned long` when declaring the function.

However, when I build MiniGUI on Ubuntu 20.04, the compiler did not report the warning or error. So this warning might cause by the different behavior of GCC.

I have fixed this and push the code.

You can update your MiniGUI from `rel-5-0` branch or upgrade your Ubuntu to 20.04 to avoid this warning.

**Comment by htk719809837** [comment]
thanks

**Comment by htk719809837** [comment]
> This compilation error caused by a typo: the type of `size` should be `size_t` instead of `unsigned long` when declaring the function.
> 
> However, when I build MiniGUI on Ubuntu 20.04, the compiler did not report the warning or error. So this warning might cause by the different behavior of GCC.
> 
> I have fixed this and push the code.
> 
> You can update your MiniGUI from `rel-5-0` branch or upgrade your Ubuntu to 20.04 to avoid this warning.

Sorry to bother you again. I upgraded the system to 20.04 and compiled it. The following error occurs when running cell phone UX demo. This problem also occurs on 18.04. But I can run mginit in mg-samples successfully.
![下载](https://user-images.githubusercontent.com/62541077/165029936-b119277c-3444-4e08-a3ce-692301f2b6cf.png)
![下载2](https://user-images.githubusercontent.com/62541077/165029942-0024b3d7-89be-4a52-80fc-aaa28462dd51.png)

**Comment by VincentWei** [comment]
Please read the error messages and check the availability of the font files. 

The font files should be contained in the `minigui-res` repo or the `cell-phone-demo` repo. Find them and run `make install` or just copy the files to the destination directory.

**Comment by htk719809837** [comment]
> 请阅读错误消息并检查字体文件的可用性。
> 
> 字体文件应包含在`minigui-res`repo 或`cell-phone-demo`repo 中。找到它们并运行`make install`或只是将文件复制到目标目录。

thank you very much ，it works well ，i will close this issues
