### ISSUE TITLE
ubuntu 18.04 enter  cell-phone-ux-demo ./mginit 报错

### ISSUE THREAD

**Issue by bill790** [VincentWei/build-minigui-5.0#18]
./mginit 
load_font_data: failed to open the font file: font/Helvetica.ttf (1)
make_devfont: error when loading font ttf-helvetica-rrncnn-0-0-ISO8859-1,GB2312-0,UTF-8 from font/Helvetica.ttf file
load_font_data: failed to open the font file: /usr/local/share/minigui/res//font/Helvetica.ttf (1)
make_devfont: error when loading font ttf-helvetica-rrncnn-0-0-ISO8859-1,GB2312-0,UTF-8 from /usr/local/share/minigui/res//font/Helvetica.ttf file
mg_InitGDI: Can not initialize fonts defined in section truetypefonts!
KERNEL>InitGUI (step 8): Initialization of GDI resource failure!

**Comment by VincentWei** [comment]
You should install `minigui-res` package to your system first.

**Comment by bill790** [comment]
solution:
sudo cp res/font/Helvetica.ttf /usr/local/share/minigui/res/font/

**Comment by bill790** [comment]
this problem caused  by the missing  "Helvetica.ttf",just copy it into /usr/local/share/minigui/res/font/
