### ISSUE TITLE
./build-deps.sh: line 22: cd: 3rd-party/harfbuzz: No such file or directory

### ISSUE THREAD

**Issue by ismaobb** [VincentWei/build-minigui-5.0#2]
CMD:./build-deps.sh
log:
BUILDING harfbuzz
./build-deps.sh: line 22: cd: 3rd-party/harfbuzz: No such file or directory
./build-deps.sh: line 23: ./autogen.sh: No such file or directory
./build-deps.sh: line 24: ./config-extern.sh: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
INSTALL MiniGUI resource files
./build-deps.sh: line 29: cd: minigui-res/: No such file or directory
./build-deps.sh: line 30: ./autogen.sh: No such file or directory

**Comment by VincentWei** [comment]
This is because that the old script did not download the dependent tarballs. Has fixed.
