### ISSUE TITLE
libmgeff的源码包里面缺少头文件

### ISSUE THREAD

**Issue by bjNong** [VincentWei/build-minigui-5.0#20]
libmgeff的源码包对比build-minigui-5.0目录下mgeff的包, src/effector目录缺少很多头文件, 导致编译不过, 这个是为什么呢 不支持effector功能吗

**Comment by VincentWei** [comment]
这个应该是由于 Makefile.am 里边遗漏了头文件导致的，先用 rel-5-0 分支的代码吧。如果方便，可以提交一个 PR。
