### ISSUE TITLE
字体不能正常显示的问题

### ISSUE THREAD

**Issue by bjNong** [VincentWei/build-minigui-5.0#21]
minigui3012的代码升级支持minigui5011的版本后,字库一样,字符和字形不能一起显示
例如:
“123你好123”
如果使用UTF8创建
CreateLogFont ("ttf", "SourceHanSansCNNormal", "UTF-8", FONT_WEIGHT_BOOK, FONT_SLANT_ROMAN,
										FONT_FLIP_NIL, FONT_OTHER_NIL, FONT_UNDERLINE_NONE, FONT_STRUCKOUT_NONE, BfontSize, 0);
这样的创建下只能显示:
123  123

如果把UTF8改成GBK
CreateLogFont ("ttf", "SourceHanSansCNNormal", "GBK", FONT_WEIGHT_BOOK, FONT_SLANT_ROMAN,
										FONT_FLIP_NIL, FONT_OTHER_NIL, FONT_UNDERLINE_NONE, FONT_STRUCKOUT_NONE, BfontSize, 0);

这样能显示:
   你好

**Comment by VincentWei** [comment]
请检查文本字符串的编码。另外请注意 5.0 的字体创建接口有一些变化，以下文档有详细描述：

https://github.com/VincentWei/minigui-docs/blob/master/supplementary-docs/Using-Enhanced-Font-Interfaces.md

**Comment by bjNong** [comment]
文本我是使用GBK格式的文件保存的，中文能正常显示，奇怪的是中文里面夹带的数字或者纯数字为什么不能直接显示？

**Comment by bjNong** [comment]
我的原程序是这样的：中文使用GBK格式的文件保存，里面会有中文，中文字符，数字等

在3012的minigui版本：
我创建的字体无论是采用GB2312还是GBK，或者UTF-8都是可以正常显示全部字符的

现在升级到5011的版本：
程序和语言文件不变，用GBK创建字体只能显示中文，这里数字都不显示就很奇怪了。
我试了把语言文件改成UTF-8格式的编码，可以把数字和中英字符、汉字都显示出来了

1、所以我现在升级后，只能说把中文的语言文件改成UTF-8编码了？

2、5011版本的minigui程序，创建的中文只能是字符编码与创建的字体格式严格对应了，不能像上述说的gbk字符串可以采用GB2312还是GBK，或者UTF-8创建？

**Comment by bjNong** [comment]
问题已经解决。Miniguicfg 配置文件对应ttf的字体处增加ISO8859-1字符集  多谢老师
