### ISSUE TITLE
SCROLLVIEW控件的DefaultItemViewProc返回值问题

### ISSUE THREAD

**Issue by bjNong** [VincentWei/build-minigui-5.0#22]
64位系统，listmode.c文件：
1、case SVM_GETITEMADDDATA返回值是DWORD
2、但是DefaultItemViewProc返回值却是int类型
3、导致设置SVM_SETITEMADDDATA的附加数据为一个地址时就会出错

**Comment by VincentWei** [comment]
Many thanks for your bug report!
