### ISSUE TITLE
KERNEL>LoadSharedResource: No such file or directory

### ISSUE THREAD

**Issue by ismaobb** [VincentWei/build-minigui-5.0#3]
env: Linux 4.15.0-96-generic
run : ./mginit
loginfo:
KERNEL>LoadSharedResource: No such file or directory
KERNEL>InitGUI (step 11): Can not load shared resource!
__mg_term_harzbuff_funcs: hb_unicode_funcs_t object is NULL
MGSlice: MemChecker: root=NULL

**Comment by VincentWei** [comment]
This is because that the old script did not download the minigui resource tarball correctly. Fixed.
