### ISSUE TITLE
docker中如何使用minigui 界面使用Framebuffer 

### ISSUE THREAD

**Issue by maikebing** [VincentWei/build-minigui-5.0#6]
由于大规模部署和应用快速切换需要， 我想通过docker部署基于minigui 的应用， 那么问题来了, 宿主机中应用正常运行， 但是docker中如何配置才能正常输出呢？或者minigui是不是可能需要支持一下这种情况？
```
 NEWGAL: Does not find matched engine: fbcon.
 MnitGUI: Can not get graphics engine information
```

**Comment by maikebing** [comment]
```
RUN   echo -e   "fbcon"  >> /etc/initramfs-tools/modules && echo -e   "vesafb"  >> /etc/initramfs-tools/modules && \
     echo -e "" >> /etc/modprobe.d/blacklist-framebuffer.conf && sed '/vesafb\|vfb/d' /etc/modprobe.d/blacklist-framebuffer.conf  
```

**Comment by VincentWei** [comment]
We need do some studies on this case. Would you like to describe the requirements in detail?

**Comment by maikebing** [comment]
目前， 我的目的是想把fb0 映射到容器内， 输入设备也映射到容器内， 所有minigui的配置和资源、依赖的所有内容都放在docker中。

**Comment by VincentWei** [comment]
If you can access the fb device in a container, you can use the environment variable `FRAMEBUFFER` to set the path name of the correct fb device, e.g.

```
export FRAMEBUFFER=/dev/your/path/to/fb0
```

BTW: I think that you should consider to user DRM engine instead of the legacy frame buffer.
